import { Category, Product } from './types';

export const MOCK_DATA: Product[] = [
    {
        id: '1',
        name: 'Whole Milk 2L',
        category: Category.DAIRY,
        expiryDate: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
        quantity: 5,
        addedDate: new Date().toISOString(),
        description: 'Fresh whole milk sourced from local farms. Ideal for daily consumption and baking.',
        price: 4.99,
        sku: 'DRY001',
        location: 'Dairy Fridge R-03',
        minStockThreshold: 10
    },
    {
        id: '2',
        name: 'Sliced Bread',
        category: Category.BAKERY,
        expiryDate: new Date(Date.now() + 86400000 * 4).toISOString().split('T')[0],
        quantity: 8,
        addedDate: new Date().toISOString(),
        description: 'Classic white sliced bread, perfect for sandwiches and toast.',
        price: 3.50,
        sku: 'BKR002',
        location: 'Bakery Shelf A-01',
        minStockThreshold: 5
    },
    {
        id: '3',
        name: 'Chicken Breast',
        category: Category.MEAT,
        expiryDate: new Date(Date.now() - 86400000).toISOString().split('T')[0],
        quantity: 2,
        addedDate: new Date().toISOString(),
        description: 'Boneless skinless chicken breast. Keep refrigerated.',
        price: 12.99,
        sku: 'MET003',
        location: 'Meat Cooler M-02',
        minStockThreshold: 5
    },
    {
        id: '4',
        name: 'Canned Beans',
        category: Category.PANTRY,
        expiryDate: new Date(Date.now() + 86400000 * 300).toISOString().split('T')[0],
        quantity: 12,
        addedDate: new Date().toISOString(),
        description: 'Premium kidney beans in tomato sauce. Great for stews and chili.',
        price: 1.20,
        sku: 'PNT004',
        location: 'Pantry Aisle 3',
        minStockThreshold: 20
    },
    {
        id: '5',
        name: 'Fresh Strawberries',
        category: Category.PRODUCE,
        expiryDate: new Date(Date.now() + 86400000 * 1).toISOString().split('T')[0],
        quantity: 15,
        addedDate: new Date().toISOString(),
        description: 'Locally grown organic strawberries. Store in a cool, dry place.',
        price: 5.49,
        sku: 'PRD005',
        location: 'Produce Section P-01',
        minStockThreshold: 8
    },
    {
        id: '6',
        name: 'Frozen Pizza Margherita',
        category: Category.FROZEN,
        expiryDate: new Date(Date.now() + 86400000 * 90).toISOString().split('T')[0],
        quantity: 6,
        addedDate: new Date().toISOString(),
        description: 'Stone-baked margherita pizza. Cook from frozen at 220°C for 12 mins.',
        price: 7.99,
        sku: 'FRZ006',
        location: 'Freezer F-05',
        minStockThreshold: 4
    },
    {
        id: '7',
        name: 'Orange Juice 1L',
        category: Category.BEVERAGE,
        expiryDate: new Date(Date.now() + 86400000 * 10).toISOString().split('T')[0],
        quantity: 20,
        addedDate: new Date().toISOString(),
        description: 'Freshly squeezed orange juice with no added sugar. Refrigerate after opening.',
        price: 3.99,
        sku: 'BEV007',
        location: 'Beverages Shelf B-02',
        minStockThreshold: 10
    },
    {
        id: '8',
        name: 'Dish Soap 500ml',
        category: Category.HOUSEHOLD,
        expiryDate: new Date(Date.now() + 86400000 * 365).toISOString().split('T')[0],
        quantity: 3,
        addedDate: new Date().toISOString(),
        description: 'Concentrated lemon-scented dish soap. Cuts through grease easily.',
        price: 2.49,
        sku: 'HSH008',
        location: 'Household Aisle H-01',
        minStockThreshold: 5
    },
    {
        id: '9',
        name: 'Greek Yogurt',
        category: Category.DAIRY,
        expiryDate: new Date(Date.now() + 86400000 * 7).toISOString().split('T')[0],
        quantity: 10,
        addedDate: new Date().toISOString(),
        description: 'Creamy full-fat Greek yogurt. Rich in protein and probiotics.',
        price: 6.49,
        sku: 'DRY009',
        location: 'Dairy Fridge R-03',
        minStockThreshold: 6
    },
    {
        id: '10',
        name: 'Organic Bananas',
        category: Category.PRODUCE,
        expiryDate: new Date(Date.now() + 86400000 * 3).toISOString().split('T')[0],
        quantity: 25,
        addedDate: new Date().toISOString(),
        description: 'Fair-trade organic bananas. Ripen at room temperature.',
        price: 1.99,
        sku: 'PRD010',
        location: 'Produce Section P-02',
        minStockThreshold: 12
    },
];
